### ISSUE TITLE
Lineage 2

### ISSUE THREAD

**Issue by linuxcz** [ivanius51/UmbrellaD2LUA#2]
Hi Ivanius here me can you contact me on? Thank you

**Comment by ivanius51** [comment]
> Hi Ivanius here xdavidoff11 can you contact me on telegram? Thank you
Hi there, cant find you. can you provide a email mb?

**Comment by linuxcz** [comment]
Hello Ivan, my email is ***@***.***

so 20. 4. 2024 v 20:12 odesílatel Ivan ***@***.***> napsal:

**Comment by ivanius51** [comment]
cant see it, my tg is @OneCorne

**Comment by ivanius51** [comment]
contacted :)
